# FROM node AS build

# WORKDIR /usr/dao

# COPY package.json package-lock.json ./

# RUN npm install

# COPY . .

# RUN npm run build

# FROM nginx:latest

# RUN rm -rf /usr/share/nginx/html/*

# COPY --from=build /usr/dao/build /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

FROM node

WORKDIR /usr/src/app

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . . 

EXPOSE 3001

CMD ["node", "app.js"]