FROM nginx

LABEL version="0.1"

WORKDIR /root

COPY . /root

RUN apt-get update && apt-get install -y nano

CMD ["cat", "helloworld.txt"]

EXPOSE 80

# docker cp C:\Users\Administrateur\Desktop\html5up-editorial . myservernginx:/root 