version: "3.8"

services:
  db:
    container_name: db
    image: mysql
    volumes:
      - db_fullstack:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tp_fullstack
    networks:
      - mysql_tp_fullstack
  
  pgadmin:
    depends_on: 
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: toto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - mysql_tp_fullstack
  
  back:
    container_name: spring_security
    ports:
      - "8080:8080"
    build:
      context: ./back
      dockerfile: dockerfile
    depends_on:
      - db
    networks:
      - mysql_tp_fullstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todolist_spring_security?createDatabaseIfNotExist=true
    
  todolist_spring:
    build:
      context: ./todolist_spring
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - mysql_tp_fullstack


volumes:
  db_fullstack:

networks:
  mysql_tp_fullstack: