FROM maven AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn package -DskipTests

FROM openjdk

WORKDIR /app

COPY --from=builder /app/target/todolist_spring_security-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "todolist_spring_security-0.0.1-SNAPSHOT.jar ."]