FROM nginx

MAINTAINER nginxfile

LABEL org.opencontainers.image.authors="myself"

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

RUN apt update && apt install -y git

RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube .

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

