version: "3.8"

services:
  db:
    image: mysql
    container_name: local_mysqldb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    volumes: 
    - local_mysqldbdata:/var/lib/mysql
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
volumes:
  local_mysqldbdata:
  phpmyadmindata:

  # docker-compose up -d
